import type { Service } from './types';

export const SERVICES: Service[] = [
  {
    id: 'airport_dfw',
    icon: '✈︎',
    name: 'Airport Transfer — DFW',
    description: 'Flight-tracked. Meet & greet included. Never wait at arrivals.',
    price: '$165',
    originalPrice: '$183',
    savings: '$18',
    priceNote: 'Flat rate · DFW Airport',
    deposit: '$83',
    depositAmount: '$83',
    fullLink:    'https://buy.stripe.com/fZubIV1kE7VBafFeCX8Vi05',
    depositLink: 'https://buy.stripe.com/00w3cp7J2b7NafF2Uf8Vi06',
  },
  {
    id: 'hourly',
    icon: '⏱',
    name: 'Hourly Charter',
    description: 'Your schedule, your route. Discreet service on your terms.',
    price: '$165/hr',
    originalPrice: '$183/hr',
    savings: '$33',
    priceNote: '2-hour minimum · $330 for 2 hrs',
    deposit: '$165',
    depositAmount: '$165',
    fullLink:    'https://buy.stripe.com/00weV72oI3FlevVfH18Vi0m',
    depositLink: 'https://buy.stripe.com/6oU5kxe7q7VB2NdamH8Vi09',
  },
  {
    id: 'wedding',
    icon: '💍',
    name: 'Wedding',
    description: 'Red carpet arrival. Complimentary décor and full-day coordination.',
    price: '$1,100',
    originalPrice: '$1,222',
    savings: '$122',
    priceNote: '8-hour · Full day package',
    deposit: '$313',
    depositAmount: '$313',
    fullLink:    'https://buy.stripe.com/aFa4gtaVe3Fl87x1Qb8Vi0a',
    depositLink: 'https://buy.stripe.com/3cIfZb4wQejZgE39iD8Vi02',
  },
  {
    id: 'prom',
    icon: '🎓',
    name: 'Prom & Events',
    description: 'Safe, on-time arrival for proms, concerts, and special occasions.',
    price: '$575',
    originalPrice: '$639',
    savings: '$64',
    priceNote: '4-hour package',
    deposit: '$288',
    depositAmount: '$288',
    fullLink:    'https://buy.stripe.com/9B6dR3gfy8ZFafFcuP8Vi0c',
    depositLink: 'https://buy.stripe.com/4gM5kx8N6b7N1J9eCX8Vi0d',
  },
  {
    id: 'night_out',
    icon: '🌙',
    name: 'Night Out',
    description: 'Dinner, drinks, and back home — without the parking or the wait.',
    price: '$475',
    originalPrice: '$528',
    savings: '$53',
    priceNote: '3-hour minimum',
    deposit: '$238',
    depositAmount: '$238',
    fullLink:    'https://buy.stripe.com/7sYeV70gAfo387xcuP8Vi0g',
    depositLink: 'https://buy.stripe.com/3cI8wJ4wQ8ZF1J91Qb8Vi0h',
  },
  {
    id: 'sporting',
    icon: '🏟',
    name: 'Sporting Events',
    description: 'Cowboys, Mavs, Stars, Rangers — door to door, zero parking stress.',
    price: '$300',
    originalPrice: '$333',
    savings: '$33',
    priceNote: 'Roundtrip',
    deposit: '$150',
    depositAmount: '$150',
    fullLink:    'https://buy.stripe.com/3cIfZb7J2cbR5Zp8ez8Vi0e',
    depositLink: 'https://buy.stripe.com/aFafZb7J2dfVevV3Yj8Vi0f',
  },
];

export const WHY_ITEMS = [
  {
    num: '01',
    title: 'On-Time Guarantee',
    body: 'We track your flight. Arrive early. If we are ever late, your ride is complimentary.',
  },
  {
    num: '02',
    title: 'Vetted Chauffeurs',
    body: 'Every chauffeur in our network is personally selected and held to the same standard.',
  },
  {
    num: '03',
    title: 'Super Cruise Technology',
    body: "The only DFW service with GM's hands-free highway driving.",
  },
  {
    num: '04',
    title: 'Flat Rate Pricing',
    body: 'No surge pricing. No surprise fees. What you see is what you pay.',
  },
  {
    num: '05',
    title: 'Absolute Discretion',
    body: 'Your conversations stay in the vehicle. The standard elite executives demand.',
  },
  {
    num: '06',
    title: 'Corporate Ready',
    body: 'Monthly invoicing, net-30 billing, COI on request. Set up as a professional vendor.',
  },
];
