import type { Service } from './types';

export const SERVICES: Service[] = [
  {
    id: 'airport_dfw',
    icon: '✈︎',
    name: 'Airport Transfer — DFW',
    description: 'Timed precisely. Flight tracking and meet & greet included.',
    price: '$165',
    priceNote: 'Flat rate · DFW Airport',
    deposit: '$83',
    depositAmount: '$83',
    fullLink:    'https://buy.stripe.com/fZubIV1kE7VBafFeCX8Vi05',
    depositLink: 'https://buy.stripe.com/00w3cp7J2b7NafF2Uf8Vi06',
  },
  {
    id: 'hourly',
    icon: '⏱',
    name: 'Hourly Charter',
    description: 'Discreet service for evenings, events, and personal travel.',
    price: '$165/hr',
    priceNote: '2-hour minimum · $330 for 2hrs',
    fullLink: 'https://buy.stripe.com/6oU5kxe7q7VB2NdamH8Vi09',
  },
  {
    id: 'wedding',
    icon: '💍',
    name: 'Wedding',
    description: 'Red carpet arrival. Complimentary décor and full coordination.',
    price: '$1,100',
    priceNote: '8-hour · Full day package',
    deposit: '$550',
    depositAmount: '$550',
    fullLink:    'https://buy.stripe.com/aFa4gtaVe3Fl87x1Qb8Vi0a',
    depositLink: 'https://buy.stripe.com/6oU00d9Ra8ZF0F5cuP8Vi0b',
  },
  {
    id: 'prom',
    icon: '🎓',
    name: 'Prom & Events',
    description: 'Professional, safe, and on time for concerts, proms, and special occasions.',
    price: '$575',
    priceNote: '4-hour package',
    deposit: '$288',
    depositAmount: '$288',
    fullLink:    'https://buy.stripe.com/9B6dR3gfy8ZFafFcuP8Vi0c',
    depositLink: 'https://buy.stripe.com/4gM5kx8N6b7N1J9eCX8Vi0d',
  },
  {
    id: 'night_out',
    icon: '🌙',
    name: 'Night Out',
    description: 'Evenings out, dinner reservations, and personal travel.',
    price: '$475',
    priceNote: '3-hour minimum',
    deposit: '$238',
    depositAmount: '$238',
    fullLink:    'https://buy.stripe.com/7sYeV70gAfo387xcuP8Vi0g',
    depositLink: 'https://buy.stripe.com/3cI8wJ4wQ8ZF1J91Qb8Vi0h',
  },
  {
    id: 'sporting',
    icon: '🏟',
    name: 'Sporting Events',
    description: 'Cowboys, Mavericks, Stars, Rangers — skip the parking.',
    price: '$300',
    priceNote: 'Roundtrip',
    deposit: '$150',
    depositAmount: '$150',
    fullLink:    'https://buy.stripe.com/3cIfZb7J2cbR5Zp8ez8Vi0e',
    depositLink: 'https://buy.stripe.com/aFafZb7J2dfVevV3Yj8Vi0f',
  },
];

export const WHY_ITEMS = [
  {
    num: '01',
    title: 'On-Time Guarantee',
    body: 'We track your flight. Arrive early. If we are ever late, your ride is complimentary.',
  },
  {
    num: '02',
    title: 'Vetted Chauffeurs',
    body: 'Every chauffeur in our network is personally selected and held to the same standard.',
  },
  {
    num: '03',
    title: 'Super Cruise Technology',
    body: "The only DFW service with GM's hands-free highway driving.",
  },
  {
    num: '04',
    title: 'Flat Rate Pricing',
    body: 'No surge pricing. No surprise fees. What you see is what you pay.',
  },
  {
    num: '05',
    title: 'Absolute Discretion',
    body: 'Your conversations stay in the vehicle. The standard elite executives demand.',
  },
  {
    num: '06',
    title: 'Corporate Ready',
    body: 'Monthly invoicing, net-30 billing, COI on request. Set up as a professional vendor.',
  },
];
